from typing import Any, Dict, Generic, Iterator, Optional, TypeVar

from .iterator import GIterator
from .model import GModel

ModelType = TypeVar("ModelType", bound=GModel)

class GModelManager(Generic[ModelType]):
    def __init__(self, model_cls: type[ModelType], setup_func: Any) -> None: ...
    def get(self, **kwargs: Any) -> ModelType: ...
    def filter(self, **kwargs: Any) -> GIterator[ModelType]: ...
    def all(self) -> GIterator[ModelType]: ...
    def reload_model(self) -> None: ...
    def initialise_model(self) -> None: ...
