from typing import Any, Generic, Iterator, Optional, TypeVar

from .model import GModel

ModelType = TypeVar("ModelType", bound=GModel)

class GIterator(Generic[ModelType]):
    def __init__(self, model_cls: type[ModelType], iterator: Iterator[Any]) -> None: ...
    def __iter__(self) -> Iterator[ModelType]: ...
    def __next__(self) -> ModelType: ...
    def __getitem__(self, key: int) -> ModelType: ...
    def first(self) -> Optional[ModelType]: ...
    def last(self) -> Optional[ModelType]: ...
    def nth(self, n: int) -> Optional[ModelType]: ...
