from typing import TypeVar, ClassVar, Any, Dict
from ._manager import GModelManager

class GModel:
    manager: ClassVar[GModelManager[Any]]
    
    def __init__(self, data: Dict[str, Any]) -> None: ...
    def to_json(self) -> Dict[str, Any]: ...
    def get_errors(self) -> Dict[str, Any]: ...
    def get_raw_data(self) -> Dict[str, Any]: ...
    def get_raw_value(self, field: str) -> Any: ...